# Generated by Django 4.0.5 on 2022-06-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageGram', '0003_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
